name: add environment variables

on:
  push:
    branches:
      - main # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: add env
        env:
          API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: |
          echo "API_KEY=${{ env.API_KEY }}" > .env
